### ISSUE TITLE
RegExp position error

### ISSUE THREAD

**Issue by hax** [veged/ometa-js#14]
ometa TestRe {
  test = /test/i,
  start = 'T',
  end = 'T',
  source = (start test end):x -> x,
}

console.log(TestRe.matchAll('TtestT', 'source'))
console.log(TestRe.matchAll('T.tesT', 'source')) // should not match!
console.log(TestRe.matchAll('T...testT', 'source')) // should match or not?

Maybe /test/i should be converted to /^test/i .

**Comment by indutny** [comment]
Thanks fixed in 79acfa2
