### ISSUE TITLE
division sign again ...

### ISSUE THREAD

**Issue by maestrow** [veged/ometa-js#16]
div.ometajs:

```
ometa CalcInterpreter {
  interp = ['num' anything:x]        -> x
         | ['add' interp:x interp:y] -> (x + y)
         | ['sub' interp:x interp:y] -> (x - y)
         | ['mul' interp:x interp:y] -> (x * y)
         | ['div' interp:x interp:y] -> (x / y)
}
// any comment line
```

ometajs2js -i div.ometajs
throws an error: Unexpected end of file, null expected.

But if remove last row (a comment), that will work.
Also if `(x / y)` replace with something without division sign, for ex `(x * y)`, that will work too.

**Comment by indutny** [comment]
Thanks, fixed!
