### ISSUE TITLE
Throw on "rule not found" instead of writing with console.error

### ISSUE THREAD

**Issue by vkz** [veged/ometa-js#30]
This bit me hard. I was catching the case of grammar failing to match when the rule is missing:

``` js
function check(ast) {
  try {
    K.match(ast, 'topLevel');
  } catch (e) {
    return false;
  }
  return true;
}

ometa K <: KIdentity {
  noTopLevelRule
}
```

but it kept throwing up and tracing. Hours later I discover this delightful thing:
https://github.com/veged/ometa-js/blob/nodejs/lib/ometajs/core/grammar.js#L168-L171

@indutny is there a good reason not to throw here? I'd rather we didn't write to **stderr** which results in much weirdness when ometa apps are run in the console, which is always. Thx

**Comment by indutny** [comment]
No reason for this, let's fix the hell out of it! ;)

**Comment by indutny** [comment]
Here you go, ometajs@4.0.0 (it was a behavior change, hence the version bump).
