### ISSUE TITLE
Use full featured JavaScript parser

### ISSUE THREAD

**Issue by veged** [veged/ometa-js#5]
According to issue https://github.com/alexwarth/ometa-js/issues/9 OmetaJS buildin parser never supposed to support all of JavaScript. So we should use some full featured JavaScript parser.

**Comment by indutny** [comment]
Implemented.

**Comment by avakarev** [comment]
Does it means that now it's possible to parse any_javascript_code?
I've tried parse jquery (not minimized) and it is fails so far. Is it ok?

``` javascript
var source = fs.readFileSync('./sample/jquery-1.7.2.js', 'UTF-8'),
      grmr    = common.ometajs.grammars.BSJSParser;
grmr.matchAll(source, 'topLevel');
```

**Comment by indutny** [comment]
Well, that means that we have some bugs over here :) Can you please post stack trace here?

**Comment by avakarev** [comment]
Yepp. I'll post each exception as a separate issue.
