### ISSUE TITLE
nodejs hangs on (~'.')+ rule

### ISSUE THREAD

**Issue by dfilatov** [veged/ometa-js#8]
Example:

```
prop
    = (~'.')+:prop -> [#prop, prop.join('')]
```

**Comment by indutny** [comment]
Thanks, fixed

**Comment by indutny** [comment]
After considering it for a second time I found that your code was simply incorrect. `~'.'` will not match anything, and eternal while loop is what one should expect in such cases. To fix that you may want to use `~'.' anything` instead.
